name = presence_footsteps
title = Rich Footsteps
description = Rich footstep sounds for Mineclonia, VoxeLibre, and Minetest Game.
optional_depends = mcl_core, mcl_sounds, mcl_wool, mcl_carpets, mcl_nether, mcl_deepslate, mcl_trees, mcl_stairs, mcl_weather, mcl_armor, mcl_boats, mcl_minecarts, mcl_amethyst, mcl_colorblocks, mcl_copper, mcl_composters, mcl_furnaces, mobs_mc, mcl_mobs, default, stairs, wool, beds, doors, xpanes, farming, flowers
supported_games = mineclonia, mineclone2, minetest_game
min_minetest_version = 5.15
